### ISSUE TITLE
Update the Tweet component with Search results

### ISSUE THREAD

**Issue by Jareechang** [Jareechang/dev-news-aggregator#1]
**Story:** 

- [x]  Upon searching, the application should display list of relevant user based on search.
- [x]  Upon clicking on a filter set of results, the tweet section should show the most recent tweets by selected user

**TODO task:**
- [ ]  Formalize API for twitter service & refactor back end (need to draw out plan)
- [ ]  Clean up the code and formalize interaction (and even additional features)
- [ ]  Update the Search functionality with current alt.js flow (search, retrieve etc)
